import 'package:audio_service/audio_service.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'dart:async';

import 'app/app.dart';
import 'core/audio/audio_handler.dart';
import 'core/db/app_database.dart';
import 'core/providers.dart';

/// App entry. Initialises Firebase, SQLite, SharedPreferences and the audio
/// background service, then hands off to [GaayanaApp].
///
/// Firebase requires `lib/firebase_options.dart` generated by:
///   `dart pub global activate flutterfire_cli`
///   `flutterfire configure`
/// We import it dynamically — if the file is missing we still boot the app
/// (auth screens will simply fail when tapped, with a clear error).
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ---- Firebase --------------------------------------------------------------
  var firebaseReady = false;
  try {
    // The standard pattern is:
    //   import 'firebase_options.dart';
    //   await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    // We do a best-effort init here so the app boots even before flutterfire
    // configure has been run for the first time.
    await Firebase.initializeApp();
    firebaseReady = true;
  } catch (e) {
    debugPrint('Firebase init skipped: $e');
  }

  // ---- Core singletons -------------------------------------------------------
  final prefs = await SharedPreferences.getInstance();
  final db = await AppDatabase.open();

  // ---- Audio background service ---------------------------------------------
  final audioHandler = await AudioService.init<GaayanaAudioHandler>(
    builder: GaayanaAudioHandler.new,
    config: const AudioServiceConfig(
      androidNotificationChannelId: 'com.gaayana.audio',
      androidNotificationChannelName: 'Gaayana playback',
      // Notification is dismissable when paused so users aren't stuck with a
      // persistent badge. It re-appears as soon as playback resumes.
      androidNotificationOngoing: false,
      androidStopForegroundOnPause: false,
      // Tapping the notification body returns to the running activity rather
      // than launching a fresh one.
      androidResumeOnClick: true,
      androidShowNotificationBadge: true,
      androidNotificationIcon: 'mipmap/ic_launcher',
    ),
  );

  // ---- Restore last queue + position (deferred so it doesn't block UI) ------
  unawaited(() async {
    try {
      final saved = await db.loadPlaybackState();
      if (saved == null) return;
      final tracks = <dynamic>[];
      for (final id in saved.ids) {
        final t = await db.trackByGlobalId(id);
        if (t != null) tracks.add(t);
      }
      if (tracks.isEmpty) return;
      await audioHandler.setQueue(
        tracks.cast(),
        initialIndex: saved.index.clamp(0, tracks.length - 1),
      );
      await audioHandler.seek(Duration(milliseconds: saved.positionMs));
      // Do NOT auto-play — wait for the user to tap play.
    } catch (e) {
      debugPrint('Restore playback failed: $e');
    }
  }());

  runApp(
    ProviderScope(
      overrides: [
        audioHandlerProvider.overrideWithValue(audioHandler),
        databaseProvider.overrideWithValue(db),
        sharedPrefsProvider.overrideWithValue(prefs),
        firebaseReadyProvider.overrideWithValue(firebaseReady),
      ],
      child: const GaayanaApp(),
    ),
  );
}
