import 'package:audio_service/audio_service.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'dart:async';
import 'dart:io' show Platform;

import 'app/app.dart';
import 'core/audio/audio_handler.dart';
import 'core/db/app_database.dart';
import 'core/debug_log.dart';
import 'core/providers.dart';

/// App entry. Initialises Firebase, SQLite, SharedPreferences and the audio
/// background service, then hands off to [GaayanaApp].
///
/// Firebase requires `lib/firebase_options.dart` generated by:
///   `dart pub global activate flutterfire_cli`
///   `flutterfire configure`
/// We import it dynamically — if the file is missing we still boot the app
/// (auth screens will simply fail when tapped, with a clear error).
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // #region agent log
  DebugLog.log('main.dart:main', 'app boot start', runId: 'run1');
  // #endregion

  // ---- Firebase --------------------------------------------------------------
  var firebaseReady = false;
  try {
    // The standard pattern is:
    //   import 'firebase_options.dart';
    //   await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    // We do a best-effort init here so the app boots even before flutterfire
    // configure has been run for the first time.
    await Firebase.initializeApp();
    firebaseReady = true;
  } catch (e) {
    debugPrint('Firebase init skipped: $e');
  }

  // ---- Core singletons -------------------------------------------------------
  final prefs = await SharedPreferences.getInstance();
  final db = await AppDatabase.open();

  // ---- Audio background service ---------------------------------------------
  // Notes from the Android media-notification docs
  // (https://developer.android.com/develop/ui/views/notifications and the
  // foreground-services / media-playback rules introduced in Android 14):
  //
  //   * The small icon MUST be a flat, monochrome silhouette on a transparent
  //     background. An adaptive launcher icon ("mipmap/ic_launcher") is
  //     dropped silently by several OEM skins (MIUI, OneUI, ColorOS) which is
  //     why the notification was never appearing.  We point at a dedicated
  //     `drawable/ic_stat_music` instead.
  //   * `androidNotificationOngoing: true` paired with
  //     `androidStopForegroundOnPause: false` keeps the foreground-service
  //     notification posted for the entire lifetime of a playback session,
  //     which is what the system requires to surface the MediaStyle
  //     lock-screen controls reliably.
  //   * A short channel description helps the system settings page describe
  //     the notification correctly so users don't disable it by accident.
  // #region agent log
  DebugLog.log('main.dart:main', 'AudioService.init begin',
      data: {'icon': 'drawable/ic_stat_music', 'ongoing': true},
      hypothesisId: 'H2',
      runId: 'run1');
  // #endregion
  final GaayanaAudioHandler audioHandler;
  try {
    audioHandler = await AudioService.init<GaayanaAudioHandler>(
      builder: GaayanaAudioHandler.new,
      config: const AudioServiceConfig(
        androidNotificationChannelId: 'com.gaayana.audio',
        androidNotificationChannelName: 'Gaayana playback',
        androidNotificationChannelDescription:
            'Media controls for the currently playing song',
        // Persistent MediaStyle notification while a song is playing.
        // audio_service enforces the invariant
        //   `!androidNotificationOngoing || androidStopForegroundOnPause`
        // (see AudioServiceConfig assert). Setting `ongoing: true` therefore
        // requires the default `stopForegroundOnPause: true`. When paused the
        // notification becomes swipe-dismissable; it re-appears on resume.
        androidNotificationOngoing: true,
        androidResumeOnClick: true,
        androidShowNotificationBadge: true,
        // Monochrome status-bar icon — see comment block above.
        androidNotificationIcon: 'drawable/ic_stat_music',
      ),
    );
    // #region agent log
    DebugLog.log('main.dart:main', 'AudioService.init OK',
        hypothesisId: 'H2', runId: 'run1');
    // #endregion
  } catch (e, s) {
    // #region agent log
    DebugLog.log('main.dart:main', 'AudioService.init FAILED',
        data: {'error': e.toString(), 'stack': s.toString()},
        hypothesisId: 'H2',
        runId: 'run1');
    // #endregion
    rethrow;
  }

  // ---- First-launch permissions --------------------------------------------
  // Notification permission (Android 13+) — the lock-screen / shade media
  // controls won't appear without this. Media-library permission is required
  // by the local-file source to scan the on-device music. Both are requested
  // before runApp so the user gets BOTH prompts on a fresh install instead of
  // discovering the missing media access only after navigating to the library.
  // Sequenced (await) rather than fire-and-forget so the second prompt is not
  // suppressed by the platform while the first is still on screen.
  try {
    final notif = await Permission.notification.request();
    // #region agent log
    DebugLog.log('main.dart:main', 'notification permission status',
        data: {
          'isGranted': notif.isGranted,
          'isDenied': notif.isDenied,
          'isPermanentlyDenied': notif.isPermanentlyDenied,
          'raw': notif.toString(),
        },
        hypothesisId: 'H1',
        runId: 'run1');
    // #endregion
    if (Platform.isAndroid) {
      // Android 13+ uses READ_MEDIA_AUDIO; older releases use
      // READ_EXTERNAL_STORAGE. Try the modern permission first; if it isn't
      // applicable (or denied) fall back to legacy storage.
      final audio = await Permission.audio.request();
      if (!(audio.isGranted || audio.isLimited)) {
        await Permission.storage.request();
      }
    } else if (Platform.isIOS) {
      await Permission.mediaLibrary.request();
    }
  } catch (e) {
    debugPrint('Permission request failed: $e');
  }

  // ---- Restore last queue + position (deferred so it doesn't block UI) ------
  unawaited(() async {
    try {
      final saved = await db.loadPlaybackState();
      if (saved == null) return;
      final tracks = <dynamic>[];
      for (final id in saved.ids) {
        final t = await db.trackByGlobalId(id);
        if (t != null) tracks.add(t);
      }
      if (tracks.isEmpty) return;
      await audioHandler.setQueue(
        tracks.cast(),
        initialIndex: saved.index.clamp(0, tracks.length - 1),
      );
      await audioHandler.seek(Duration(milliseconds: saved.positionMs));
      // Do NOT auto-play — wait for the user to tap play.
    } catch (e) {
      debugPrint('Restore playback failed: $e');
    }
  }());

  runApp(
    ProviderScope(
      overrides: [
        audioHandlerProvider.overrideWithValue(audioHandler),
        databaseProvider.overrideWithValue(db),
        sharedPrefsProvider.overrideWithValue(prefs),
        firebaseReadyProvider.overrideWithValue(firebaseReady),
      ],
      // #region agent log
      child: const DebugHudOverlay(child: GaayanaApp()),
      // #endregion
    ),
  );
}
