import 'package:audio_service/audio_service.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'app/app.dart';
import 'core/audio/audio_handler.dart';
import 'core/db/app_database.dart';
import 'core/providers.dart';

/// App entry. Initialises Firebase, SQLite, SharedPreferences and the audio
/// background service, then hands off to [GaayanaApp].
///
/// Firebase requires `lib/firebase_options.dart` generated by:
///   `dart pub global activate flutterfire_cli`
///   `flutterfire configure`
/// We import it dynamically — if the file is missing we still boot the app
/// (auth screens will simply fail when tapped, with a clear error).
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ---- Firebase --------------------------------------------------------------
  var firebaseReady = false;
  try {
    // The standard pattern is:
    //   import 'firebase_options.dart';
    //   await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    // We do a best-effort init here so the app boots even before flutterfire
    // configure has been run for the first time.
    await Firebase.initializeApp();
    firebaseReady = true;
  } catch (e) {
    debugPrint('Firebase init skipped: $e');
  }

  // ---- Core singletons -------------------------------------------------------
  final prefs = await SharedPreferences.getInstance();
  final db = await AppDatabase.open();

  // ---- Audio background service ---------------------------------------------
  final audioHandler = await AudioService.init<GaayanaAudioHandler>(
    builder: GaayanaAudioHandler.new,
    config: const AudioServiceConfig(
      androidNotificationChannelId: 'com.gaayana.audio',
      androidNotificationChannelName: 'Gaayana playback',
      androidNotificationOngoing: true,
      androidStopForegroundOnPause: true,
      androidNotificationIcon: 'mipmap/ic_launcher',
    ),
  );

  runApp(
    ProviderScope(
      overrides: [
        audioHandlerProvider.overrideWithValue(audioHandler),
        databaseProvider.overrideWithValue(db),
        sharedPrefsProvider.overrideWithValue(prefs),
        firebaseReadyProvider.overrideWithValue(firebaseReady),
      ],
      child: const GaayanaApp(),
    ),
  );
}
